from flask import Flask, render_template, request, Blueprint

# Initialize the Blueprint
home_remedies = Blueprint('home_remedies', __name__, template_folder="templates")

# Define sample home remedies
remedies = {
    'Cold & Flu': 'Drink warm fluids like ginger tea, and inhale steam with eucalyptus oil to clear nasal passages.',
    'Headache': 'Apply peppermint oil to your temples or drink chamomile tea to reduce headache symptoms.',
    'Sore Throat': 'Gargle with warm salt water and drink honey mixed in warm water for soothing relief.',
    'Stomach Ache': 'Consume peppermint or ginger tea to reduce discomfort and promote digestion.',
    'Deafness': 'Use raw onion juice as ear drops. Put two drops of lukewarm neem oil inside the ear.',
    'Indigestion':'5-6 gm. powder of fried Jeera and rock-salt with warm water thrice daily.',
    'Headache':'Warm paste should be applied over forehead upto 3 times a day.To be rubbed with water on a rough surface & applied to fore head.',
    'Fever':'2 gm. powder with honey twice daily.30 ml decoction from handful of leaves & 5 gm. Dhania thrice a day.',
    'Cold/Cough':'2-5 gm. powder of dry rhizome with jaggery thrice a day in divided doses. 10ml. decoction prepared from a piece of ginger every morning prevents recurrent attack of cold.2 gm.haldi powder with warm milk and sugar twice a day.',
    'Acidity':'Take a tiny piece of jaggery (gur) every hour. Just keep it in the mouth and slowly suck it till acidity subsides.',
    'Acne':'coconut water 3-4 times a day. Have a plateful of watermelon (Clean face with cotton wool dipped in rose water 2-3 times a day. Do not use soap. Orange peel is very good in the treatment of acne. Grind the peel with some water to a paste and apply on affected parts. when oranges are not in season, you may use a powder of dried orange peels. For this, when oranges are in season, dry orange peels in shade. Powder finely in a grinder and sift it to make it a very fine powder. Store in an air tight bottle for future use. Mix 1 teaspoon lemon juice in 1 teaspoon finely ground cinnamon (dalchini) powder and apply on affected areas frequently. Sift the cinnamon (dalchini) powder to make it into a very fine powder. Crush a fegarlic (lasan) flakes and apply on the face, once or twice a day. Swallowing 1-2 flakes of ragarlic regularly helps further. Grind some neem leaves with water to a fine paste. Apply on infected area. Make a paste of Â½ teaspoon each of sandalwood and turmeric (haldi) powder in a little water and apply.',
    'Anaemia':'Avoid drinking tea and coffee immediately after meals as the tannin present in these interferes in the absorption of iron from the food.  Take freshly prepared apple juice an hour before meals or just before retiring for the night. For proper absorption of the juice, remember the stomach should be relatively empty when you have the juice and also do not take anything for about half an hour after the juice. Juice of beetroot taken 1-2 times daily is an excellent remedy for anaemia especially for children and teenagers. You may combine apple and beetroot for the juice. Mix 1 tablespoon amla juice with a ripe mashed banana and eat 2-3 times a day. Have a ripe banana with 1 tablespoon honey, 1-2 times a day. Soak 8-10 almonds (badam) and 1 teaspoon rice overnight. Remove outer skin of almonds and grind to a fine paste. Boil with 1Â½ cups of milk and a pinch of turmeric powder (haldi). Sweeten with sugar and drink for a fedays, once a day. Soak 10-12 currants (munakas) in water overnight. Remove seeds and eat them. Have for 2-4 weeks. Have spinach juice of 125 gm spinach everyday, for 2-3 weeks. Foods rich in iron are - honey, almonds, bananas, apricots (khurmani), raisins (kishmish), fenugreek (methi) leaves, fenugreek seeds (methi daana), lettuce or salad leaves, onion, spinach (paalak), grapes, tomatoes, carrots, gooseberry (amla), beetroots (chokunder), apples, pomegranate (anaar). Have plenty of them if you are anaemic.',
    'Angina Pectoris':	'Thoroughly mix 2 teaspoons almond oil with 1 teaspoon rose oil. Rub gently on the chest, morning and evening. Boil 1 teaspoon fenugreek seeds (methi dana) in 1Â½ cups water. Strain and add 2 teaspoon honey. Take twice daily.',
    'Animal bite':	'Take Â½ teaspoon ground black cumin seeds (shah jeera), twice daily. Ankle - swelling & pain Mix equal quantities of castor oil and lime juice. Massage the affected area with this mixture. Also drink 1 cup warm water mixed with lime juice and honey.',
    'Appetite loss (Anorexia)':	'Mix and powder equal quantities of carom seeds (ajwain), fennel seeds (saunf), dried ginger powder (sonth), salt and black cumin seeds (shah jeera).Mix a teaspoon of this } powder and a teaspoon of hot ghee to cooked rice and eat frequently . Take 2 teaspoon of amla juice and mix it with 2 teaspoon honey and 2 teaspoon lime juice. Add 1 cup water and drink on an empty stomach every morning. To take out juice from fresh amla, remove seeds from fresh amla and grind the pulp into a fine paste. Tie it in a muslin cloth and squeeze out the juice. whenever fresh fruits are not available, dried amla can be used. Soak 1 tablespoon of dried amla at night in a cup of water. Strain it the next morning. Add 1/8 teaspoon black pepper powder (kali Mirch) and 2 teaspoon lime juice. Dilute it if necessary with water and drink every morning regularly on an empty stomach. Take Â½ teaspoon black pepper powder (kali mirch) and 1 tablespoon jaggery powder (shakkar) mixed together. Kali mirch Cut 1"" piece ginger (adrak) into small pieces. Add 1Â½ cups of water. Boil. Simmer for 2-3 minutes. Add milk and sugar to taste, and take it frequently like tea.',
    'Asthma':'Mix 1 teaspoon honey with Â½ teaspoon cinnamon (dalchini) powder and have at night before going to bed. Boil carom seeds (ajwain) in water and inhale the steam. Boil 8-10 flakes of garlic (lasan) in Â½ cup of milk. Have this every night. Gives excellent results in early stages of asthma. Add a handful of drumstick leaves (sahijan) to 1 cup water. Boil. Simmer on loflame for 3-4 minutes. Cool and strain. Add salt, pepper and lemon juice to taste. Have every day, once or twice a day. wAn expectorant and a very effective remedy for asthma is prepared by boiling 6 cloves (laung) in 3 tablespoons of water. Take 1 teaspoon of this decoction with a little honey, thrice daily. Mix Â¼ teaspoon asafetida (hing), 2 teaspoon honey, Â½ teaspoon juice from betel leaf (paan ka patta), Â½ teaspoon white onion juice. Have it 2-3 times a day. To take out juice from betel leaf, Clove flowers crush to a paste and squeeze through a clean muslin cloth. For onion juice, grate the onion and squeeze through a clean muslin cloth. Mix equal amounts of fresh ginger (adrak) juice, honey & pomegranate (anaar) juice. Take 1 tablespoon, 1-2 times a day. Figs (anjeer) are known to give relief by draining the phlegm (balgam). Take 3-4 dry figs, wash them well with warm water. Soak overnight in a cup of water. Eat them first thing in the morning and also drink the water. Do this for at least 2 months.',
    'Backache':'Rub some ginger paste on the affected area. Apply oil of eucalyptus on it.',
    'Bad Odour':'Use neem twigs as tooth paste. Powder the dried mint (pudina) leaves. Use as toothpowder.',
    'Baldness':'Boil 1 cup mustard oil (sarson ka tel) with 4 tablespoon henna (mehendi) leaves. Filter and bottle. Massage on the bald patches regularly. Grind the remains of tobacco smoked in a hookah and add to boiling mustard oil. Cool and store. Massage on the bald patches regularly. Rub on the scalp 1 teaspoon oil in which raw mangoes have been preserved for over one year. Repeat this treatment frequently. Grind 1 tablespoon liquorice root pieces (mulathi) in 1 cup milk with Â¼ teaspoon saffron (kesar). Apply this paste on bald patches at bedtime continuously. Grind fenugreek seeds (methi dana), with water and apply on the head. Leave for at least 40 minutes before washing. Do it every morning for a month. Bed sores w Apply honey on the length and breadth of a banana leaf and lie on it for a few hours. Ensure its contact with the affected parts.',	
    'Bed wetting in children':'Give 2 walnut halves (akhrot giri) and 1 teaspoon of kishmish to the child before sleeping for 10-12 days. Belching (dakaar) Grind 2 teaspoon each carom seeds (ajwain) and dried ginger (adrak) into a fine powder. Add a little black salt (kala namak). Take 1 teaspoon of this mixture with 1 cup warm water frequently.',
    'Blackheads':'Mix 1 teaspoon lime juice in 1 teaspoon finely ground cinnamon (dalchini) powder and apply on affected areas frequently. Mix 1 teaspoon each turmeric (haldi) powder and juice of fresh coriander (dhania) leaves and apply daily as a face pack before going to sleep.',
    'Bladder Stones':'Boil 2 figs (anjeer) in 1 cup of water. Drink daily for a month.',
    'Blood Deficiency':'Take 2 teaspoon of amla juice and mix it with two teaspoonfuls each of honey and lime. Add 1 teacup water and drink on an empty stomach every morning. Whenever fresh fruits are not available, dried amla can be used. Soak 1 tablespoon the previous night in a cup of water. (Note: The treatment should continue for at least 120 days to achieve expected results.) Mix 1 tablespoon juice of amla with a ripe mashed banana and eat twice or three times a day. Soak 2 or 3 dried figs (anjeer) in 1 teacup water. Eat them along with milk next morning for a month. Blood pressure _ lowHave juice of 10-15 basil (tulsi) leaves mixed with 1 teaspoon honey. Crush the leaves to a paste and squeeze out the juice through a muslin cloth. blood pressure - high  See "HIGH BLOOD PRESSURE" on page 60 Blood sugar w Take 2-3 garlic (lasan) cloves for a few days regularly. Body and Muscles developmentSoak 2 almonds, 5 pista kernels and 1 teaspoon poppy seeds (khuskhus) in 1 cup cows milk for an hour. Grind. Add some more warm milk. Take daily for 3 months. Body dry itch Grind 1 tablespoon poppy seeds (khuskhus) with 1 teaspoon water. Add 1 teaspoon lime juice. Apply on the affected areas.',
    'Dental Problems':'Turmeric (haldi), burnt, and finely powdered, can be used as toothpowder.',
    'Delivery Of Babies':'Mix 3 teaspoon lime juice, Â¼ teaspoon powdered black pepper and 1 teaspoon honey in 1 cup water. Drink for 3 months.',
    'Diarrhea':'Combine 1 teaspoon each powdered ginger (adrak), powdered cumin (jeera) and powdered cinnamon (dalchini) with honey and make into a thick paste. Take 1 teaspoon thrice daily. Boil 1 teaspoon cumin seeds (jeera) in a glass of water. Add to this 1 teaspoon fresh juice of coriander leaves (dhania) and a pinch of salt. Drink twice daily after meals for 2-3 days. Mash 1 ripe banana along with a pinch of salt and 1 teaspoon tamarind pulp (imli ka guda). Take twice a day. Drinking a strong cup of unsweetened black tea is very effective for stopping diarrhoea. Peel an apple and shred it. Keep the shredded pieces in a plate for approximately 20 minutes until they turn brown in colour, and then eat them. Slice the tender unripe bel fruit. Sun dry them. Powder the slices. Take 1 teaspoon along with warm water twice a day. Take every night, 3 cloves of garlic (lasan), chopped and boiled in milk. Make a paste of 1 green chilli along with 2 tablespoon lime juice and Â½ teaspoon camphor (kapur). Take Â¼ teaspoon of this paste. 2 or 3 teaspoon coriander seeds (saboot dhania) soaked overnight in water and taken next morning with 1 cup buttermilk (chhach). Boil Â¼ teaspoon powdered cardamom (chhoti illaichi) seeds in thin tea water and drink. Mix juice of 15-20 tender curry leaves (curry patta) with 1 teaspoon honey and drink. Apply ginger (adrak) juice around the navel. Insert Â¼ teaspoon nutmeg (jaiphal) powder inside a ripe banana and eat.',
    'Diarrhea due to indigestion of food':'Insert Â¼ teaspoon nutmeg (jaiphal) powder inside a ripe banana and eat. Dog-bite Take Â½ teaspoon powder of black cumin seeds (shah jeera) twice daily.',
    'Ear Infection':'Extract 1 teaspoon juice from mango leaves. Slightly warm and use as ear drops when bearably hot.Boils inside Ear.Heat 2 teaspoon mustard oil. Add Â½ teaspoon carom (ajwain) seeds and one or two flakes of crushed garlic (lasan). Boil till they turn red. Filter. Use as ear drops.',
    'Eye Aching':'Powder equal quantities of liquorice (mulathi) and cumin (jeera). Take Â¼ teaspoon every day along with 1 teaspoon honey for a month. Eyes burning w Mash 1 ripe banana along with a little curd and water; take twice a day. Mix equal quantities of fenugreek seed (methi daana) powder along with Shikakai powder for washing hair. Wash frequently. Grind an onion with 1 teaspoon each black pepper and poppy seeds (khuskhus) soaked in Â½ cup milk. Apply this paste on the head. Allow it to dry for 15-20 minutes. Wash in warm water. Mix the juice of bottle gourd (karela) and sesame oil (til ka tel) in the ratio of 4:1, and heat till the moisture is evaporated completely. Once cool, use it for massaging the head.',
    'Exhaustion due to overwork':'Boil Â¼ teaspoon powdered cardamom (chhoti illaichi) seeds in thin tea water and drink.',
    'Epilepsy':'Apply fresh lime juice on the head. Massage well before showering off.',
    'Eyes Having Dark Circles Around Them':	'Take one teaspoon tomato juice, Â½ teaspoon lemon juice, a pinch of turmeric (haldi) powder & a little gram flour (besan). Make a paste & apply. Leave for 10 minute & wash off. Drink tomato juice with a few mint leaves, little lemon juice & salt w Soak cotton wool in cucumber (kheera) or potato juice & apply around the eyes. You will find a change in 2-3 weeks. Eyes strain due to TV watching Boil Â½ teaspoon fennel seeds (saunf) in a cup of water till it is reduced to half. Cool. Use as eye drops (Caution: Beware of contamination).',
    'Tired Eyes':'Lavender oil offers gentle relief for tired and strained eyes. Add a drop of lavender oil to 500 ml (2Â½ cups) of water and shake the solution well. Dip two cotton wool pads in the liquid, squeeze out the excess water and place one pad over each eye. If you wear contact lenses, they must be removed beforehand.',
    'Eyesight Weakness':'Mix seeds of cardamom (chhoti illaichi) along with 1 tablespoon honey. Eat every day. Boil 2 tablespoon fenugreek (methi) leaves along with Â½ cup moong dal and 10 small onions and eat regularly. Mix equal quantities of fenugreek seeds (methi dana) powder along with Shikakai powder for washing hair. Wash frequently.',
    'Fainting':'A hot poultice of carom seeds (ajwain) used as dry fomentation for hands and feet.',
    'Fatigue':'Take a glass of grapefruit and lemon juice in equal parts to dispel fatigue and general tiredness after a days work.',
    'Feet Burning':'Mash 1 ripe banana along with a little curd and water; take twice a day.',
    'Feet / Sole Having Cracks':'Mix equal quantities of glycerin and lemon juice. Apply every night before going to bed. This mixture can be made and stored in a glass bottle. Massage your feet with castor oil every night (in winters) for 2-3 minutes and then wear socks at night. Grind equal amounts of neem leaves & turmeric (haldi). Apply on affected area. Finely grind a handful of henna (mehendi) leaves. Add 2 tablespoon lemon juice and apply on the feet. Mix the juice of bottle gourd (lauki) and sesame oil (til ka tel) in the ratio 4:1 and heat till all the moisture has evaporated. Bottle and use over cracked skin.',
    'Feet Smelling':'Soak feet in strong tea for 20 minutes every day until the smell disappears. To prepare your footbath, brew two tea bags in 500 ml (2Â½ cups) of water for 15 minutes and pour the tea into a basin containing two litres of cool water.',
    'Foot Corns':'Tie a fresh slice of lemon over the corn (painful area) and keep it all night. Massage castor oil on the corns every morning and night before sleeping. Massage for 2-3 minutes so that the oil gets absorbed. In 3-4 weeks the corns will disappear. Mash 1-2 cloves (laung) & garlic (lasan) and tie over the corns. Keep overnight.',
    'Athletes Foot':'Keeping your feet clean and dry is enough to discourage the growth of this fungal infection. Remember, it is infectious and you must keep and wash your shoes, socks and towel separately. To soothe the broken areas of your feet, simply soak them for 10 minutes in a footbath of apple cider vinegar mixed with water.',
    'Flatulence':'Soak 3 tablespoon carom (ajwain) seeds in an adequate quantity of lime juice and dry in the shade. When fully dried, powder with a little black salt. Take 1 teaspoon of this mixture twice daily for a few days with a little warm water.',
    'Fever':'Extract 1 teaspoon each juice of tulsi leaves and bel flowers. Add 1 teaspoon honey. Take twice a day. Tea made by boiling 1 teaspoon fenugreek seeds (methi dana), taken twice or thrice a day provides excellent remedy. (A little honey or lemon juice can be added to improve the flavour). Grind a few roots of the mango tree into a fine paste and apply on the palm and soles of the patients. The neem leaf decoction taken with pepper powder lowers temperature. Â½ teaspoon ground pepper is mixed in warm water along with 1 teaspoon palm candy (sugar obtained from palm). This drink is taken at bedtime. w Fruit juice taken frequently. Regular intake of a pinch of saffron (kesar). Apply sandalwood paste on the forehead to bring the temperature down. Boil 2 tablespoon fennel seeds (saunf) in 1 teacup water till it is reduced to half. Filter. Take 1 tablespoon every morning and evening for a few days. (This filtrate, when used to wash the eyes frequently, is reported to strengthen the eye muscles. It is a good cleansing lotion for inflamed eyes.).',
    'Fever of unknown origin':'Boil 1 tablespoon tulsi leaves with 1 teaspoon powdered cardamom (chhoti illaichi) in 2 teacups water. Take 1 cup of this decoction with milk and sugar to taste 2 or 3 times a day.',
    'Feverishness':'Mix 1 teacup fresh lemon juice in tender coconut water and drink.',
    'Gas Problem':'Some people are allergic or have intolerance for milk, milk products and wheat, wheat products but go through life without ever realizing this and keep suffering from acute gas trouble. Lactose intolerance (from milk) is being recognized in the west as also gluten intolerance (from wheat). Hence giving up these two things may greatly benefit you. Instead of wheat you can have rice or chapatis of maize, jawar or bajara. w Mix Â¼ teaspoon dry ginger powder (sonth) with a pinch of asafoetida (hing).',
    'Golden Rules for Gas Patients':'Avoid heavy (fried), spicy food. Do not eat very large meals, instead eat small meals. Try to eat a little, every 2 hours, so that the gap between the meals is not too big. Do some exercise. Even a walk will do wonders.',
    'Gastroenteritis':'A decoction of 15-20 tulsi leaves taken along with a pinch of rock salt (kala namak) helps in the cure.',
    'Giddiness':'Soak cumin seeds (jeera) in lime juice overnight. Keep this mixture under the sun till completely dry. Bottle it. Chew Â½ teaspoon of this mixture and drink with a glass of warm water.',
    'Giddiness due to blood pressure':'Soak 1 teaspoon each of powdered amla, coriander seeds (saboot dhania) and sandalwood in a cup of water overnight. Strain and drink the next day. Continue for a few days.',
    'Gouty Pains':'Mix mustard oil and rectified alcohol (1 part oil to 40 parts alcohol) and use as a lotion. Make a poultice of ground fenugreek seeds (methi dana); use on the affected part.',
    'Hair Dullness And Coarseness':'Grind fresh fenugreek leaves (methi) to a paste and apply the leaf paste over the scalp before a bath.',
    'Hair Falling':'Take a handful of neem leaves and boil them in 4 cups water. After cooling and filtering, use the decoction for rinsing hair. Mix equal quantities of dried curry leaves (curry patta), lime peel (nimbu ka chilka), Shikakai, fenugreek seeds (methi daana) & green gram (moong saboot) and grind them finely. Store and use as a substitute for soap or shampoo. Apply fenugreek (methi) seeds, ground with some water and the paste on the head. Allow to soak at least for 40 minutes before washing. Use every morning for a month.',
    'Hair Loss':'Apply a little almond oil (badam ka tel) on scalp frequently and massage.',
    'Hair Greying':'Wet a lemon half and rub lemon juice into the scalp well. Wash off after it turns dry. Grind 1 tablespoon each, pulp of amla and lime juice. Massage this into the hair before going to bed. Wash it next morning. Soak shredded ginger (adrak) in honey. Eat a spoonful every morning.',
    'Hair Thinning':'Bathe the hair in 1 cup coconut milk twice or thrice a week for a few months.',
    'Head heaviness':'Grind the fresh amla fruits into a fine paste and apply on affected parts. Grind 2 to 3 cloves (laung) into a fine paste along with Â½ teaspoon dried ginger (sonth) and apply on nose, forehead, etc.',
    'Headache':'Roast some ajwain dry on a tawa. Tie it in a muslin bag and sniff frequently. Make a paste of 2-3 powdered cloves (laung) and salt. Apply this paste on the forehead. A paste made of dry ginger (sonth) with a little water or milk when applied to the forehead also gives relief. A ripe apple, after removing the upper rind and the inner hard portion should be taken with a little salt every morning on an empty stomach. Continue for a week. This yields good results even in case of chronic headaches. Mix 1 teaspoon finely ground cinnamon (dalchini) in 1 teaspoon water and apply on the forehead. It is very effective in headache due to exposure to cold air. Crush an onion and apply the paste on the head. Grind 10-15 tulsi leaves with 4 cloves (laung) and 1 teaspoon dried ginger (sonth) into a paste and apply.',
    'Headache due to exposure to cold air':'Mix 1 teaspoon finely ground cinnamon (dalchini) in 1 teaspoon water and apply on the affected parts. Headache on one side w Powder equal quantities of liquorice (mulathi) and cumin (jeera). Take Â¼ teaspoon every day along with 1 teaspoon honey for a month. Mix 1 teaspoon each of the following powders and store: camphor (kapoor), nutmeg (jaiphal), cardamom (chhoti illaichi) and cloves (laung). Take 2 pinches with warm water. Heart attack w Take Â½ teaspoon garlic (lasan) powder every day.',
    'Heart burn':'Add 1 tablespoon mint (pudina) leaves to 1 cup water. Take twice or thrice a day.',
    'Heart pain':'Boil Â½ teaspoon sandalwood powder in 1 cup water. Drink thrice daily.',
    'Heart palpitation':'Boil Â¼ teaspoon powdered cardamom (chhoti illaichi) seeds in thin tea water and drink.',
    'Heart problem':'Eat Â¼ teaspoon asafetida (hing) along with one large raisin (kishmish) every day. Heart weakness w Regular intake of ripe bananas strengthens the heart.',
    'Heat exhaustion':'Apply some sandalwood oil on the forehead.',
    'Heat stroke':'Have the cooling drink panna. To prepare this, cook unripe or green mangoes in hot ashes. Extract the pulp and mix with water and sugar. You may even pressure cook the mangoes if you cannot make provision for the ashes.',
    'Heels having pain':'Mix equal amounts by weight of carom seeds (ajwain), onion seeds (kalaunji) fenugreek seeds (methi daana) and saboot isabgol. Have 1 tablespoon every day first thing in the morning. If you like you can grind them slightly in the mixer - makes it more effective. This treatment takes a couple of months but is a sure shot remedy.',
    'Hepatitis':'1 to 2 teaspoon fresh juice of coriander (dhania) leaves is mixed in 1 cup buttermilk and taken 2-3 times.',
    'Hiccups':'Drink Â½ glass water, slowly. w Keep a teaspoon of sugar in your month and suck slowly. Swallow Â½ teaspoon mustard seeds (sarson) mixed with Â½ teaspoon pure ghee. Grind 4 cardamom (chhoti illaichi) well. Boil it in 2Â½ cups or Â½ litre water. When about 1 cup water remains, remove from fire and sieve it through a muslin cloth. Let it cool. When warm, drink a glassful. Works like magic. Suck 2-3 small pieces of fresh ginger (adrak). This helps in hiccups which keep occurring again and again.',
    'High Blood Pressure':'Restrict salt intake and drink plenty of fluids (at least 8-10 glasses of water daily) Drink curry leaves (curry patta) juice initially 3 times a day (1 glassful) for 1- 2 months and then reduce to only once in the morning. Have it on empty stomach. For taking out juice: fill your mixy with washed curry leaves, add Â½3/4 glass water. Churn well and sieve. Add Â½ - 1 lemon juice and drink fresh. Have single pod garlic (lasan), one pod first thing every morning or if this is not available, have 1-2 cloves of ordinary garlic (lasan). If you get discomfort with having garlic first thing in the morning, have 2 cloves twice a day - swallow with water any time or with meals. Mix 1 teaspoon honey, 1 teaspoon ginger (adrak) juice, 1 teaspoon cumin (jeera) powder. Have twice a day. Go on an apple diet for a few days. It has a diuretic effect and thus brings down the B.P. Fruits such as mausami, orange, peaches (aaru), plum (aloo bukhara), watermelon (tarbooz) are also beneficial. Having rice, particularly brown rice as the main staple food is very beneficial. As rice has very low sodium content and low cholesterol, it is a perfect diet for those who have been advised to have low salt diets. Consumption of natural diuretics like coconut water, butter milk, coriander (dhania) juice (make from green coriander in the same way as curry leaves juice) is very beneficial. Last but not the least, rest, relaxation and good sleep are effective in keeping B.P. under control. Drink coriander (dhania) juice made from fresh dhania (same way as curry leaves juices) 3 times a day. If this is not effective, start having fenugreek (methi) juice instead (made from fresh methi) and if this is also not effective, move to curry leaves juice. Drink each juice for 10-12 days at least before you decide. If it is not working and then move to the next one.',
    'Body Heat':'Add 2 to 3 drops of almonds oil to pomegranate (anaar) juice and drink. Soak 8 to 10 almonds and 1 teaspoon rice overnight. Remove the outer skin. Grind into a fine paste. Mix with some milk and add a pinch of turmeric powder (haldi) and sugar candy (mishri) to taste. Boil and drink. Remove seeds from fresh amla fruits and grind the pulp into a fine paste. Tie it in a muslin cloth and squeeze out the juice. Take 2 teaspoon of this juice and mix it with two teaspoonfuls each honey and lime juice. Add 1 cup water and drink on an empty stomach every morning. Take a tender bel fruit. Grind it with 1 cup milk. Apply on the head and massage well before taking a shower.',
}

# Blueprint routes
@home_remedies.route('/')
def remedies_home():
    return render_template("home_remedies.html", remedies=list(remedies.keys()))

@home_remedies.route('/get_remedy', methods=['POST'])
def get_remedy():
    selected_ailment = request.form.get('disease')
    remedy = remedies.get(selected_ailment, 'No remedy available.')
    return render_template("home_remedies.html", 
                         remedies=list(remedies.keys()), 
                         selected_ailment=selected_ailment, 
                         remedy=remedy)

# Create Flask App
app = Flask(__name__)

# Register Blueprint
app.register_blueprint(home_remedies, url_prefix='/home_remedies')

# Main app route
@app.route('/')
def home():
    return render_template('index.html')

if __name__ == '__main__':
    app.run(debug=True)